### ISSUE TITLE
直接使用你的ini可以吗？

### ISSUE THREAD

**Issue by dingwf** [Lotusice/Clash_Rules#1]
直接使用你的ini，发现生成的YAML里面还是没有你定义的这个几个。我是用了：https://acl4ssr-sub.github.io/， https://id9.cc/

**Comment by c8kh2necaamm** [comment]
当然可以，这个是自用的，只适用于我的用途。如果有其它不同的分流需求，可以fork一份自己定制。
需要将ini的RAW链接（如该项目的：https://raw.githubusercontent.com/Lotusice/Clash_Rules/main/custom_rules.ini ）
放入订阅转换中「远程配置」这一栏

该项目fork自：https://github.com/Wzieee/custom-network-rules
